#!/usr/bin/env bash
# Regenerate src/integrations/supabase/types.ts from the LOCAL verification database.
#
# The Supabase CLI's `gen types --db-url` shells out to Docker; this script uses the
# same generator (@supabase/postgres-meta) directly so it works anywhere psql does.
#
# Usage:  bun run db:reset && bun run db:types
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
URL="${LOCAL_DATABASE_URL:-postgres://postgres:postgres@localhost:5432/rentid_local}"
OUT="${ROOT}/src/integrations/supabase/types.ts"
CACHE="${ROOT}/node_modules/.cache/pgmeta"
PORT="${PG_META_PORT:-18085}"

if [ ! -d "${CACHE}/node_modules/@supabase/postgres-meta" ]; then
  echo "==> Installing @supabase/postgres-meta into ${CACHE}"
  mkdir -p "${CACHE}"
  (cd "${CACHE}" && [ -f package.json ] || npm init -y >/dev/null)
  (cd "${CACHE}" && npm install --no-audit --no-fund --silent @supabase/postgres-meta@latest >/dev/null)
fi

echo "==> Starting postgres-meta on :${PORT}"
PG_META_DB_URL="${URL}" PG_META_PORT="${PORT}" PG_META_ADMIN_PORT=$((PORT + 1)) \
  node "${CACHE}/node_modules/@supabase/postgres-meta/dist/server/server.js" >"${CACHE}/server.log" 2>&1 &
PID=$!
trap 'kill ${PID} >/dev/null 2>&1 || true' EXIT

for _ in $(seq 1 40); do
  if curl -fs "http://127.0.0.1:${PORT}/health" >/dev/null 2>&1; then break; fi
  sleep 0.25
done

TMP="$(mktemp)"
curl -fs "http://127.0.0.1:${PORT}/generators/typescript?included_schemas=public&detect_one_to_one_relationships=true" -o "${TMP}"

{
  echo "// Generated by scripts/db/gen-types.sh from the local verification database."
  echo "// Do not edit by hand: change a migration, run \`bun run db:reset && bun run db:types\`."
  cat "${TMP}"
} > "${OUT}"
rm -f "${TMP}"

echo "==> Wrote $(wc -l < "${OUT}") lines to ${OUT#${ROOT}/}"
