/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForLandlordsRouteImport } from './routes/for-landlords'
import { Route as ForPropertyManagersRouteImport } from './routes/for-property-managers'
import { Route as ForTenantsRouteImport } from './routes/for-tenants'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTenantRouteImport } from './routes/_authenticated/tenant'
import { Route as ApplyListingRefRouteImport } from './routes/apply.$listingRef'
import { Route as ListingListingRefRouteImport } from './routes/listing.$listingRef'
import { Route as ProvidersOrgIdRouteImport } from './routes/providers.$orgId'
import { Route as RentIndexRouteImport } from './routes/rent.index'
import { Route as RentListingIdRouteImport } from './routes/rent.$listingId'
import { Route as AuthenticatedAdminProspectsRouteImport } from './routes/_authenticated/admin.prospects'
import { Route as AuthenticatedAdminVerificationRouteImport } from './routes/_authenticated/admin.verification'
import { Route as AuthenticatedLeasesIndexRouteImport } from './routes/_authenticated/leases.index'
import { Route as AuthenticatedLeasesLeaseIdRouteImport } from './routes/_authenticated/leases.$leaseId'
import { Route as AuthenticatedListingsIndexRouteImport } from './routes/_authenticated/listings.index'
import { Route as AuthenticatedListingsListingIdRouteImport } from './routes/_authenticated/listings.$listingId'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedManagerListingsRouteImport } from './routes/_authenticated/manager.listings'
import { Route as AuthenticatedManagerOwnersRouteImport } from './routes/_authenticated/manager.owners'
import { Route as AuthenticatedManagerPortfolioRouteImport } from './routes/_authenticated/manager.portfolio'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties.index'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties.$propertyId'
import { Route as AuthenticatedTenantIndexRouteImport } from './routes/_authenticated/tenant.index'
import { Route as AuthenticatedTenantHousingRouteImport } from './routes/_authenticated/tenant.housing'
import { Route as AuthenticatedTenantLeaseRouteImport } from './routes/_authenticated/tenant.lease'
import { Route as AuthenticatedTenantMaintenanceRouteImport } from './routes/_authenticated/tenant.maintenance'
import { Route as AuthenticatedTenantMessagesRouteImport } from './routes/_authenticated/tenant.messages'
import { Route as AuthenticatedTenantPayRouteImport } from './routes/_authenticated/tenant.pay'
import { Route as AuthenticatedTenantProfileRouteImport } from './routes/_authenticated/tenant.profile'
import { Route as AuthenticatedTenantTenancyRouteImport } from './routes/_authenticated/tenant.tenancy'
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants.index'
import { Route as AuthenticatedTenantsTenancyIdRouteImport } from './routes/_authenticated/tenants.$tenancyId'
import { Route as AuthenticatedUnitsIndexRouteImport } from './routes/_authenticated/units.index'
import { Route as AuthenticatedManagerStudentIndexRouteImport } from './routes/_authenticated/manager.student.index'
import { Route as AuthenticatedManagerStudentChangesRouteImport } from './routes/_authenticated/manager.student.changes'
import { Route as AuthenticatedManagerStudentPreleasingRouteImport } from './routes/_authenticated/manager.student.preleasing'
import { Route as AuthenticatedManagerStudentTurnoverRouteImport } from './routes/_authenticated/manager.student.turnover'
import { Route as AuthenticatedManagerStudentUnitsUnitIdRouteImport } from './routes/_authenticated/manager.student.units.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForLandlordsRoute = ForLandlordsRouteImport.update({
  id: '/for-landlords',
  path: '/for-landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPropertyManagersRoute = ForPropertyManagersRouteImport.update({
  id: '/for-property-managers',
  path: '/for-property-managers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTenantsRoute = ForTenantsRouteImport.update({
  id: '/for-tenants',
  path: '/for-tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantRoute = AuthenticatedTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApplyListingRefRoute = ApplyListingRefRouteImport.update({
  id: '/apply/$listingRef',
  path: '/apply/$listingRef',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingListingRefRoute = ListingListingRefRouteImport.update({
  id: '/listing/$listingRef',
  path: '/listing/$listingRef',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersOrgIdRoute = ProvidersOrgIdRouteImport.update({
  id: '/providers/$orgId',
  path: '/providers/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/rent/',
  path: '/rent/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentListingIdRoute = RentListingIdRouteImport.update({
  id: '/rent/$listingId',
  path: '/rent/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProspectsRoute =
  AuthenticatedAdminProspectsRouteImport.update({
    id: '/prospects',
    path: '/prospects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVerificationRoute =
  AuthenticatedAdminVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedLeasesIndexRoute =
  AuthenticatedLeasesIndexRouteImport.update({
    id: '/leases/',
    path: '/leases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeasesLeaseIdRoute =
  AuthenticatedLeasesLeaseIdRouteImport.update({
    id: '/leases/$leaseId',
    path: '/leases/$leaseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsIndexRoute =
  AuthenticatedListingsIndexRouteImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsListingIdRoute =
  AuthenticatedListingsListingIdRouteImport.update({
    id: '/listings/$listingId',
    path: '/listings/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerListingsRoute =
  AuthenticatedManagerListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerOwnersRoute =
  AuthenticatedManagerOwnersRouteImport.update({
    id: '/owners',
    path: '/owners',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerPortfolioRoute =
  AuthenticatedManagerPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantIndexRoute =
  AuthenticatedTenantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantHousingRoute =
  AuthenticatedTenantHousingRouteImport.update({
    id: '/housing',
    path: '/housing',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantLeaseRoute =
  AuthenticatedTenantLeaseRouteImport.update({
    id: '/lease',
    path: '/lease',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantMaintenanceRoute =
  AuthenticatedTenantMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantMessagesRoute =
  AuthenticatedTenantMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantPayRoute = AuthenticatedTenantPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AuthenticatedTenantRoute,
} as any)
const AuthenticatedTenantProfileRoute =
  AuthenticatedTenantProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantTenancyRoute =
  AuthenticatedTenantTenancyRouteImport.update({
    id: '/tenancy',
    path: '/tenancy',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantsIndexRoute =
  AuthenticatedTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantsTenancyIdRoute =
  AuthenticatedTenantsTenancyIdRouteImport.update({
    id: '/tenants/$tenancyId',
    path: '/tenants/$tenancyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUnitsIndexRoute = AuthenticatedUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerStudentIndexRoute =
  AuthenticatedManagerStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerStudentChangesRoute =
  AuthenticatedManagerStudentChangesRouteImport.update({
    id: '/student/changes',
    path: '/student/changes',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerStudentPreleasingRoute =
  AuthenticatedManagerStudentPreleasingRouteImport.update({
    id: '/student/preleasing',
    path: '/student/preleasing',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerStudentTurnoverRoute =
  AuthenticatedManagerStudentTurnoverRouteImport.update({
    id: '/student/turnover',
    path: '/student/turnover',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerStudentUnitsUnitIdRoute =
  AuthenticatedManagerStudentUnitsUnitIdRouteImport.update({
    id: '/student/units/$unitId',
    path: '/student/units/$unitId',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/for-property-managers': typeof ForPropertyManagersRoute
  '/for-tenants': typeof ForTenantsRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/manager': typeof AuthenticatedManagerRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenant': typeof AuthenticatedTenantRouteWithChildren
  '/apply/$listingRef': typeof ApplyListingRefRoute
  '/listing/$listingRef': typeof ListingListingRefRoute
  '/providers/$orgId': typeof ProvidersOrgIdRoute
  '/rent/$listingId': typeof RentListingIdRoute
  '/rent/': typeof RentIndexRoute
  '/admin/prospects': typeof AuthenticatedAdminProspectsRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/leases/$leaseId': typeof AuthenticatedLeasesLeaseIdRoute
  '/listings/$listingId': typeof AuthenticatedListingsListingIdRoute
  '/manager/listings': typeof AuthenticatedManagerListingsRoute
  '/manager/owners': typeof AuthenticatedManagerOwnersRoute
  '/manager/portfolio': typeof AuthenticatedManagerPortfolioRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/tenant/housing': typeof AuthenticatedTenantHousingRoute
  '/tenant/lease': typeof AuthenticatedTenantLeaseRoute
  '/tenant/maintenance': typeof AuthenticatedTenantMaintenanceRoute
  '/tenant/messages': typeof AuthenticatedTenantMessagesRoute
  '/tenant/pay': typeof AuthenticatedTenantPayRoute
  '/tenant/profile': typeof AuthenticatedTenantProfileRoute
  '/tenant/tenancy': typeof AuthenticatedTenantTenancyRoute
  '/tenants/$tenancyId': typeof AuthenticatedTenantsTenancyIdRoute
  '/leases/': typeof AuthenticatedLeasesIndexRoute
  '/listings/': typeof AuthenticatedListingsIndexRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/tenant/': typeof AuthenticatedTenantIndexRoute
  '/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/units/': typeof AuthenticatedUnitsIndexRoute
  '/manager/student/changes': typeof AuthenticatedManagerStudentChangesRoute
  '/manager/student/preleasing': typeof AuthenticatedManagerStudentPreleasingRoute
  '/manager/student/turnover': typeof AuthenticatedManagerStudentTurnoverRoute
  '/manager/student/': typeof AuthenticatedManagerStudentIndexRoute
  '/manager/student/units/$unitId': typeof AuthenticatedManagerStudentUnitsUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/for-property-managers': typeof ForPropertyManagersRoute
  '/for-tenants': typeof ForTenantsRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/apply/$listingRef': typeof ApplyListingRefRoute
  '/listing/$listingRef': typeof ListingListingRefRoute
  '/providers/$orgId': typeof ProvidersOrgIdRoute
  '/rent/$listingId': typeof RentListingIdRoute
  '/rent': typeof RentIndexRoute
  '/admin/prospects': typeof AuthenticatedAdminProspectsRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/leases/$leaseId': typeof AuthenticatedLeasesLeaseIdRoute
  '/listings/$listingId': typeof AuthenticatedListingsListingIdRoute
  '/manager/listings': typeof AuthenticatedManagerListingsRoute
  '/manager/owners': typeof AuthenticatedManagerOwnersRoute
  '/manager/portfolio': typeof AuthenticatedManagerPortfolioRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/tenant/housing': typeof AuthenticatedTenantHousingRoute
  '/tenant/lease': typeof AuthenticatedTenantLeaseRoute
  '/tenant/maintenance': typeof AuthenticatedTenantMaintenanceRoute
  '/tenant/messages': typeof AuthenticatedTenantMessagesRoute
  '/tenant/pay': typeof AuthenticatedTenantPayRoute
  '/tenant/profile': typeof AuthenticatedTenantProfileRoute
  '/tenant/tenancy': typeof AuthenticatedTenantTenancyRoute
  '/tenants/$tenancyId': typeof AuthenticatedTenantsTenancyIdRoute
  '/leases': typeof AuthenticatedLeasesIndexRoute
  '/listings': typeof AuthenticatedListingsIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/tenant': typeof AuthenticatedTenantIndexRoute
  '/tenants': typeof AuthenticatedTenantsIndexRoute
  '/units': typeof AuthenticatedUnitsIndexRoute
  '/manager/student/changes': typeof AuthenticatedManagerStudentChangesRoute
  '/manager/student/preleasing': typeof AuthenticatedManagerStudentPreleasingRoute
  '/manager/student/turnover': typeof AuthenticatedManagerStudentTurnoverRoute
  '/manager/student': typeof AuthenticatedManagerStudentIndexRoute
  '/manager/student/units/$unitId': typeof AuthenticatedManagerStudentUnitsUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/for-property-managers': typeof ForPropertyManagersRoute
  '/for-tenants': typeof ForTenantsRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tenant': typeof AuthenticatedTenantRouteWithChildren
  '/apply/$listingRef': typeof ApplyListingRefRoute
  '/listing/$listingRef': typeof ListingListingRefRoute
  '/providers/$orgId': typeof ProvidersOrgIdRoute
  '/rent/$listingId': typeof RentListingIdRoute
  '/rent/': typeof RentIndexRoute
  '/_authenticated/admin/prospects': typeof AuthenticatedAdminProspectsRoute
  '/_authenticated/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/_authenticated/leases/$leaseId': typeof AuthenticatedLeasesLeaseIdRoute
  '/_authenticated/listings/$listingId': typeof AuthenticatedListingsListingIdRoute
  '/_authenticated/manager/listings': typeof AuthenticatedManagerListingsRoute
  '/_authenticated/manager/owners': typeof AuthenticatedManagerOwnersRoute
  '/_authenticated/manager/portfolio': typeof AuthenticatedManagerPortfolioRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/_authenticated/tenant/housing': typeof AuthenticatedTenantHousingRoute
  '/_authenticated/tenant/lease': typeof AuthenticatedTenantLeaseRoute
  '/_authenticated/tenant/maintenance': typeof AuthenticatedTenantMaintenanceRoute
  '/_authenticated/tenant/messages': typeof AuthenticatedTenantMessagesRoute
  '/_authenticated/tenant/pay': typeof AuthenticatedTenantPayRoute
  '/_authenticated/tenant/profile': typeof AuthenticatedTenantProfileRoute
  '/_authenticated/tenant/tenancy': typeof AuthenticatedTenantTenancyRoute
  '/_authenticated/tenants/$tenancyId': typeof AuthenticatedTenantsTenancyIdRoute
  '/_authenticated/leases/': typeof AuthenticatedLeasesIndexRoute
  '/_authenticated/listings/': typeof AuthenticatedListingsIndexRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/tenant/': typeof AuthenticatedTenantIndexRoute
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/_authenticated/units/': typeof AuthenticatedUnitsIndexRoute
  '/_authenticated/manager/student/changes': typeof AuthenticatedManagerStudentChangesRoute
  '/_authenticated/manager/student/preleasing': typeof AuthenticatedManagerStudentPreleasingRoute
  '/_authenticated/manager/student/turnover': typeof AuthenticatedManagerStudentTurnoverRoute
  '/_authenticated/manager/student/': typeof AuthenticatedManagerStudentIndexRoute
  '/_authenticated/manager/student/units/$unitId': typeof AuthenticatedManagerStudentUnitsUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/for-landlords'
    | '/for-property-managers'
    | '/for-tenants'
    | '/invite'
    | '/join'
    | '/admin'
    | '/applications'
    | '/dashboard'
    | '/documents'
    | '/maintenance'
    | '/manager'
    | '/messages'
    | '/onboarding'
    | '/payments'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/tenant'
    | '/apply/$listingRef'
    | '/listing/$listingRef'
    | '/providers/$orgId'
    | '/rent/$listingId'
    | '/rent/'
    | '/admin/prospects'
    | '/admin/verification'
    | '/leases/$leaseId'
    | '/listings/$listingId'
    | '/manager/listings'
    | '/manager/owners'
    | '/manager/portfolio'
    | '/properties/$propertyId'
    | '/tenant/housing'
    | '/tenant/lease'
    | '/tenant/maintenance'
    | '/tenant/messages'
    | '/tenant/pay'
    | '/tenant/profile'
    | '/tenant/tenancy'
    | '/tenants/$tenancyId'
    | '/leases/'
    | '/listings/'
    | '/manager/'
    | '/properties/'
    | '/tenant/'
    | '/tenants/'
    | '/units/'
    | '/manager/student/changes'
    | '/manager/student/preleasing'
    | '/manager/student/turnover'
    | '/manager/student/'
    | '/manager/student/units/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/for-landlords'
    | '/for-property-managers'
    | '/for-tenants'
    | '/invite'
    | '/join'
    | '/admin'
    | '/applications'
    | '/dashboard'
    | '/documents'
    | '/maintenance'
    | '/messages'
    | '/onboarding'
    | '/payments'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/apply/$listingRef'
    | '/listing/$listingRef'
    | '/providers/$orgId'
    | '/rent/$listingId'
    | '/rent'
    | '/admin/prospects'
    | '/admin/verification'
    | '/leases/$leaseId'
    | '/listings/$listingId'
    | '/manager/listings'
    | '/manager/owners'
    | '/manager/portfolio'
    | '/properties/$propertyId'
    | '/tenant/housing'
    | '/tenant/lease'
    | '/tenant/maintenance'
    | '/tenant/messages'
    | '/tenant/pay'
    | '/tenant/profile'
    | '/tenant/tenancy'
    | '/tenants/$tenancyId'
    | '/leases'
    | '/listings'
    | '/manager'
    | '/properties'
    | '/tenant'
    | '/tenants'
    | '/units'
    | '/manager/student/changes'
    | '/manager/student/preleasing'
    | '/manager/student/turnover'
    | '/manager/student'
    | '/manager/student/units/$unitId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/for-landlords'
    | '/for-property-managers'
    | '/for-tenants'
    | '/invite'
    | '/join'
    | '/_authenticated/admin'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/maintenance'
    | '/_authenticated/manager'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/payments'
    | '/_authenticated/reports'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/tenant'
    | '/apply/$listingRef'
    | '/listing/$listingRef'
    | '/providers/$orgId'
    | '/rent/$listingId'
    | '/rent/'
    | '/_authenticated/admin/prospects'
    | '/_authenticated/admin/verification'
    | '/_authenticated/leases/$leaseId'
    | '/_authenticated/listings/$listingId'
    | '/_authenticated/manager/listings'
    | '/_authenticated/manager/owners'
    | '/_authenticated/manager/portfolio'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/tenant/housing'
    | '/_authenticated/tenant/lease'
    | '/_authenticated/tenant/maintenance'
    | '/_authenticated/tenant/messages'
    | '/_authenticated/tenant/pay'
    | '/_authenticated/tenant/profile'
    | '/_authenticated/tenant/tenancy'
    | '/_authenticated/tenants/$tenancyId'
    | '/_authenticated/leases/'
    | '/_authenticated/listings/'
    | '/_authenticated/manager/'
    | '/_authenticated/properties/'
    | '/_authenticated/tenant/'
    | '/_authenticated/tenants/'
    | '/_authenticated/units/'
    | '/_authenticated/manager/student/changes'
    | '/_authenticated/manager/student/preleasing'
    | '/_authenticated/manager/student/turnover'
    | '/_authenticated/manager/student/'
    | '/_authenticated/manager/student/units/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForLandlordsRoute: typeof ForLandlordsRoute
  ForPropertyManagersRoute: typeof ForPropertyManagersRoute
  ForTenantsRoute: typeof ForTenantsRoute
  InviteRoute: typeof InviteRoute
  JoinRoute: typeof JoinRoute
  ApplyListingRefRoute: typeof ApplyListingRefRoute
  ListingListingRefRoute: typeof ListingListingRefRoute
  ProvidersOrgIdRoute: typeof ProvidersOrgIdRoute
  RentListingIdRoute: typeof RentListingIdRoute
  RentIndexRoute: typeof RentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-landlords': {
      id: '/for-landlords'
      path: '/for-landlords'
      fullPath: '/for-landlords'
      preLoaderRoute: typeof ForLandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-property-managers': {
      id: '/for-property-managers'
      path: '/for-property-managers'
      fullPath: '/for-property-managers'
      preLoaderRoute: typeof ForPropertyManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-tenants': {
      id: '/for-tenants'
      path: '/for-tenants'
      fullPath: '/for-tenants'
      preLoaderRoute: typeof ForTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant': {
      id: '/_authenticated/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof AuthenticatedTenantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apply/$listingRef': {
      id: '/apply/$listingRef'
      path: '/apply/$listingRef'
      fullPath: '/apply/$listingRef'
      preLoaderRoute: typeof ApplyListingRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$listingRef': {
      id: '/listing/$listingRef'
      path: '/listing/$listingRef'
      fullPath: '/listing/$listingRef'
      preLoaderRoute: typeof ListingListingRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$orgId': {
      id: '/providers/$orgId'
      path: '/providers/$orgId'
      fullPath: '/providers/$orgId'
      preLoaderRoute: typeof ProvidersOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/': {
      id: '/rent/'
      path: '/rent'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$listingId': {
      id: '/rent/$listingId'
      path: '/rent/$listingId'
      fullPath: '/rent/$listingId'
      preLoaderRoute: typeof RentListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/prospects': {
      id: '/_authenticated/admin/prospects'
      path: '/prospects'
      fullPath: '/admin/prospects'
      preLoaderRoute: typeof AuthenticatedAdminProspectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/verification': {
      id: '/_authenticated/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AuthenticatedAdminVerificationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/leases/': {
      id: '/_authenticated/leases/'
      path: '/leases'
      fullPath: '/leases/'
      preLoaderRoute: typeof AuthenticatedLeasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leases/$leaseId': {
      id: '/_authenticated/leases/$leaseId'
      path: '/leases/$leaseId'
      fullPath: '/leases/$leaseId'
      preLoaderRoute: typeof AuthenticatedLeasesLeaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/': {
      id: '/_authenticated/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof AuthenticatedListingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/$listingId': {
      id: '/_authenticated/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof AuthenticatedListingsListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/listings': {
      id: '/_authenticated/manager/listings'
      path: '/listings'
      fullPath: '/manager/listings'
      preLoaderRoute: typeof AuthenticatedManagerListingsRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/owners': {
      id: '/_authenticated/manager/owners'
      path: '/owners'
      fullPath: '/manager/owners'
      preLoaderRoute: typeof AuthenticatedManagerOwnersRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/portfolio': {
      id: '/_authenticated/manager/portfolio'
      path: '/portfolio'
      fullPath: '/manager/portfolio'
      preLoaderRoute: typeof AuthenticatedManagerPortfolioRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant/': {
      id: '/_authenticated/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof AuthenticatedTenantIndexRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/housing': {
      id: '/_authenticated/tenant/housing'
      path: '/housing'
      fullPath: '/tenant/housing'
      preLoaderRoute: typeof AuthenticatedTenantHousingRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/lease': {
      id: '/_authenticated/tenant/lease'
      path: '/lease'
      fullPath: '/tenant/lease'
      preLoaderRoute: typeof AuthenticatedTenantLeaseRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/maintenance': {
      id: '/_authenticated/tenant/maintenance'
      path: '/maintenance'
      fullPath: '/tenant/maintenance'
      preLoaderRoute: typeof AuthenticatedTenantMaintenanceRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/messages': {
      id: '/_authenticated/tenant/messages'
      path: '/messages'
      fullPath: '/tenant/messages'
      preLoaderRoute: typeof AuthenticatedTenantMessagesRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/pay': {
      id: '/_authenticated/tenant/pay'
      path: '/pay'
      fullPath: '/tenant/pay'
      preLoaderRoute: typeof AuthenticatedTenantPayRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/profile': {
      id: '/_authenticated/tenant/profile'
      path: '/profile'
      fullPath: '/tenant/profile'
      preLoaderRoute: typeof AuthenticatedTenantProfileRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/tenancy': {
      id: '/_authenticated/tenant/tenancy'
      path: '/tenancy'
      fullPath: '/tenant/tenancy'
      preLoaderRoute: typeof AuthenticatedTenantTenancyRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/$tenancyId': {
      id: '/_authenticated/tenants/$tenancyId'
      path: '/tenants/$tenancyId'
      fullPath: '/tenants/$tenancyId'
      preLoaderRoute: typeof AuthenticatedTenantsTenancyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units/': {
      id: '/_authenticated/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof AuthenticatedUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/student/': {
      id: '/_authenticated/manager/student/'
      path: '/student'
      fullPath: '/manager/student/'
      preLoaderRoute: typeof AuthenticatedManagerStudentIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/student/changes': {
      id: '/_authenticated/manager/student/changes'
      path: '/student/changes'
      fullPath: '/manager/student/changes'
      preLoaderRoute: typeof AuthenticatedManagerStudentChangesRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/student/preleasing': {
      id: '/_authenticated/manager/student/preleasing'
      path: '/student/preleasing'
      fullPath: '/manager/student/preleasing'
      preLoaderRoute: typeof AuthenticatedManagerStudentPreleasingRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/student/turnover': {
      id: '/_authenticated/manager/student/turnover'
      path: '/student/turnover'
      fullPath: '/manager/student/turnover'
      preLoaderRoute: typeof AuthenticatedManagerStudentTurnoverRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/student/units/$unitId': {
      id: '/_authenticated/manager/student/units/$unitId'
      path: '/student/units/$unitId'
      fullPath: '/manager/student/units/$unitId'
      preLoaderRoute: typeof AuthenticatedManagerStudentUnitsUnitIdRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminProspectsRoute: typeof AuthenticatedAdminProspectsRoute
  AuthenticatedAdminVerificationRoute: typeof AuthenticatedAdminVerificationRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminProspectsRoute: AuthenticatedAdminProspectsRoute,
  AuthenticatedAdminVerificationRoute: AuthenticatedAdminVerificationRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedManagerRouteChildren {
  AuthenticatedManagerListingsRoute: typeof AuthenticatedManagerListingsRoute
  AuthenticatedManagerOwnersRoute: typeof AuthenticatedManagerOwnersRoute
  AuthenticatedManagerPortfolioRoute: typeof AuthenticatedManagerPortfolioRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
  AuthenticatedManagerStudentChangesRoute: typeof AuthenticatedManagerStudentChangesRoute
  AuthenticatedManagerStudentPreleasingRoute: typeof AuthenticatedManagerStudentPreleasingRoute
  AuthenticatedManagerStudentTurnoverRoute: typeof AuthenticatedManagerStudentTurnoverRoute
  AuthenticatedManagerStudentIndexRoute: typeof AuthenticatedManagerStudentIndexRoute
  AuthenticatedManagerStudentUnitsUnitIdRoute: typeof AuthenticatedManagerStudentUnitsUnitIdRoute
}

const AuthenticatedManagerRouteChildren: AuthenticatedManagerRouteChildren = {
  AuthenticatedManagerListingsRoute: AuthenticatedManagerListingsRoute,
  AuthenticatedManagerOwnersRoute: AuthenticatedManagerOwnersRoute,
  AuthenticatedManagerPortfolioRoute: AuthenticatedManagerPortfolioRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
  AuthenticatedManagerStudentChangesRoute:
    AuthenticatedManagerStudentChangesRoute,
  AuthenticatedManagerStudentPreleasingRoute:
    AuthenticatedManagerStudentPreleasingRoute,
  AuthenticatedManagerStudentTurnoverRoute:
    AuthenticatedManagerStudentTurnoverRoute,
  AuthenticatedManagerStudentIndexRoute: AuthenticatedManagerStudentIndexRoute,
  AuthenticatedManagerStudentUnitsUnitIdRoute:
    AuthenticatedManagerStudentUnitsUnitIdRoute,
}

const AuthenticatedManagerRouteWithChildren =
  AuthenticatedManagerRoute._addFileChildren(AuthenticatedManagerRouteChildren)

interface AuthenticatedTenantRouteChildren {
  AuthenticatedTenantHousingRoute: typeof AuthenticatedTenantHousingRoute
  AuthenticatedTenantLeaseRoute: typeof AuthenticatedTenantLeaseRoute
  AuthenticatedTenantMaintenanceRoute: typeof AuthenticatedTenantMaintenanceRoute
  AuthenticatedTenantMessagesRoute: typeof AuthenticatedTenantMessagesRoute
  AuthenticatedTenantPayRoute: typeof AuthenticatedTenantPayRoute
  AuthenticatedTenantProfileRoute: typeof AuthenticatedTenantProfileRoute
  AuthenticatedTenantTenancyRoute: typeof AuthenticatedTenantTenancyRoute
  AuthenticatedTenantIndexRoute: typeof AuthenticatedTenantIndexRoute
}

const AuthenticatedTenantRouteChildren: AuthenticatedTenantRouteChildren = {
  AuthenticatedTenantHousingRoute: AuthenticatedTenantHousingRoute,
  AuthenticatedTenantLeaseRoute: AuthenticatedTenantLeaseRoute,
  AuthenticatedTenantMaintenanceRoute: AuthenticatedTenantMaintenanceRoute,
  AuthenticatedTenantMessagesRoute: AuthenticatedTenantMessagesRoute,
  AuthenticatedTenantPayRoute: AuthenticatedTenantPayRoute,
  AuthenticatedTenantProfileRoute: AuthenticatedTenantProfileRoute,
  AuthenticatedTenantTenancyRoute: AuthenticatedTenantTenancyRoute,
  AuthenticatedTenantIndexRoute: AuthenticatedTenantIndexRoute,
}

const AuthenticatedTenantRouteWithChildren =
  AuthenticatedTenantRoute._addFileChildren(AuthenticatedTenantRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTenantRoute: typeof AuthenticatedTenantRouteWithChildren
  AuthenticatedLeasesLeaseIdRoute: typeof AuthenticatedLeasesLeaseIdRoute
  AuthenticatedListingsListingIdRoute: typeof AuthenticatedListingsListingIdRoute
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRoute
  AuthenticatedTenantsTenancyIdRoute: typeof AuthenticatedTenantsTenancyIdRoute
  AuthenticatedLeasesIndexRoute: typeof AuthenticatedLeasesIndexRoute
  AuthenticatedListingsIndexRoute: typeof AuthenticatedListingsIndexRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute
  AuthenticatedUnitsIndexRoute: typeof AuthenticatedUnitsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTenantRoute: AuthenticatedTenantRouteWithChildren,
  AuthenticatedLeasesLeaseIdRoute: AuthenticatedLeasesLeaseIdRoute,
  AuthenticatedListingsListingIdRoute: AuthenticatedListingsListingIdRoute,
  AuthenticatedPropertiesPropertyIdRoute:
    AuthenticatedPropertiesPropertyIdRoute,
  AuthenticatedTenantsTenancyIdRoute: AuthenticatedTenantsTenancyIdRoute,
  AuthenticatedLeasesIndexRoute: AuthenticatedLeasesIndexRoute,
  AuthenticatedListingsIndexRoute: AuthenticatedListingsIndexRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
  AuthenticatedUnitsIndexRoute: AuthenticatedUnitsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForLandlordsRoute: ForLandlordsRoute,
  ForPropertyManagersRoute: ForPropertyManagersRoute,
  ForTenantsRoute: ForTenantsRoute,
  InviteRoute: InviteRoute,
  JoinRoute: JoinRoute,
  ApplyListingRefRoute: ApplyListingRefRoute,
  ListingListingRefRoute: ListingListingRefRoute,
  ProvidersOrgIdRoute: ProvidersOrgIdRoute,
  RentListingIdRoute: RentListingIdRoute,
  RentIndexRoute: RentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
